config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resource :phone, controller: 'user_phones' do
      post 'verify', on: :collection
      post 'resend_verification_code', on: :collection
    end
    resource :email, controller: 'user_emails' do
      post 'resend_verification_code', on: :collection
    end
  end
  get  '/scrape/:league',        to: 'games#scrape'
  post '/games',                 to: 'games#retrieve_given_params'
  post '/zip_codes',             to: 'user_zip_codes#update'
  post '/retrieve_zip',          to: 'user_zip_codes#show'
  post '/update_favorite_teams', to: 'user_favorite_teams#update_all'
  post '/verify_email',          to: 'user_emails#verify'
  post '/unsubscribe_email',     to: 'user_emails#unsubscribe'

  resources :games
  resources :users, only: [:create]
  resources :teams do
    resources :nicknames
  end
  resources :user_notification_preferences, only: [:index, :create, :destroy, :update, :show]
  resources  :user_favorite_teams
  namespace :admin do
    resources :users
    resources :user_notification_preferences
    get '/upcoming_notifications',  to: 'user_notification_preferences#upcoming_notifications'
  end

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '*path', to: "application#fallback_index_html", constraints: ->(request) do
    !request.xhr? && request.format.html?
  end
end

app/models/nickname.rb
class Nickname < ApplicationRecord
  belongs_to :team

  scope :with_league, ->(league) { where(league: league.downcase) if league.present?}
end

app/controllers/nicknames_controller.rb
class NicknamesController < AdminController
  before_action :set_nickname, only: [:show, :edit, :update, :destroy]

  # GET /nicknames
  # GET /nicknames.json
  def index
    @nicknames = Nickname.all
  end

  # GET /nicknames/1
  # GET /nicknames/1.json
  def show
  end

  # GET /nicknames/new
  def new
    @nickname = Nickname.new
  end

  # GET /nicknames/1/edit
  def edit
  end

  # POST /nicknames
  # POST /nicknames.json
  def create
    @nickname = Nickname.new(nickname_params)

    respond_to do |format|
      if @nickname.save
        format.html { redirect_to @nickname, notice: 'Nickname was successfully created.' }
        format.json { render :show, status: :created, location: @nickname }
      else
        format.html { render :new }
        format.json { render json: @nickname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nicknames/1
  # PATCH/PUT /nicknames/1.json
  def update
    respond_to do |format|
      if @nickname.update(nickname_params)
        format.html { redirect_to @nickname, notice: 'Nickname was successfully updated.' }
        format.json { render :show, status: :ok, location: @nickname }
      else
        format.html { render :edit }
        format.json { render json: @nickname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nicknames/1
  # DELETE /nicknames/1.json
  def destroy
    @nickname.destroy
    respond_to do |format|
      format.html { redirect_to nicknames_url, notice: 'Nickname was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_nickname
    @nickname = Nickname.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def nickname_params
    params.require(:nickname).permit(:name, :team_id)
  end
end

app/views/nicknames/_form.html.haml
= form_for @nickname do |f|
  - if @nickname.errors.any?
    #error_explanation
      %h2= "#{pluralize(@nickname.errors.count, "error")} prohibited this nickname from being saved:"
      %ul
        - @nickname.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :team_id
    = f.number_field :team_id
  .actions
    = f.submit 'Save'

app/views/nicknames/edit.html.haml
%h1 Editing nickname

= render 'form'

= link_to 'Show', @nickname
\|
= link_to 'Back', nicknames_path

app/views/nicknames/index.html.haml
%h1 Listing nicknames

%table
  %thead
    %tr
      %th Name
      %th Team
      %th
      %th
      %th

  %tbody
    - @nicknames.each do |nickname|
      %tr
        %td= nickname.name
        %td= nickname.team_id
        %td= link_to 'Show', nickname
        %td= link_to 'Edit', edit_nickname_path(nickname)
        %td= link_to 'Destroy', nickname, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Nickname', new_nickname_path

app/views/nicknames/new.html.haml
%h1 New nickname

= render 'form'

= link_to 'Back', nicknames_path

app/views/nicknames/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @nickname.name
%p
  %b Team:
  = @nickname.team_id

= link_to 'Edit', edit_nickname_path(@nickname)
\|
= link_to 'Back', nicknames_path